#!/bin/bash
LAUNCH_FILES="stage1.launch robot.launch"
DELAY=5
PIDPATH=${HOME}/.ros

pidname() {
    echo ${PIDPATH}/$(basename ${1} .launch).pid
}

case ${1} in
    start)
        shift
        for launch in ${LAUNCH_FILES}; do
            roslaunch --pid=$(pidname ${launch}) samplereturn ${launch} "$@" &
            sleep ${DELAY}
        done
        ;;
    stop)
        for launch in ${LAUNCH_FILES}; do
            kill -INT $(cat $(pidname ${launch}))
        done
        ;;
    *)
        echo "Must specify \"start\" or \"stop\" as first argument"
        exit 1
        ;;
esac 
