#camera ignore params, to allow testing without certain cameras
executive_master:
    ignore_search_camera: True
    ignore_manipulator_camera: True
        
level_two:
    #for search  behaviour, degrees and meters
    move_velocity: 1.0
    spin_velocity: 0.5
    spoke_count: 20 
    max_spoke_length: 200 
    first_spoke_offset: 90 
    next_spoke_sign: 1 # 1 for ccw, -1 for cw
    spoke_hub_radius: 15
    #raster step is distance between raster lines
    #raster offset is how close to the spoke we get
    #before we go to the next raster step
    raster_step: 6
    raster_offset: 6
    raster_tolerance: 1.5 #close enough to next point?
    chord_course_tolerance: 3.0 #what is off course on a chord move
    return_time_minutes: 110 
    #dismount and beacon approach
    dismount_move: {angle: 0, distance: 6.0, velocity: 0.5}
    beacon_approach_point: {x: 6.0, y: 0}
    platform_point: {x: -0.9, y: 0.0}
    beacon_observation_delay: 10 
    beacon_calibration_delay: 20
    gyro_calibration_delay: 10
    beacon_mount_tolerance: 0.02 #correction must be less than this before mount
    #if a planned point has changed more than this, replan.
    #if greater than recalibrate, wait and observe beacon, and set gyro bias
    replan_threshold: 2.0
    recalibrate_threshold: 5.0    
    #for costmap issues, set to zero to disable this
    blocked_retry_delay: 3.0

pursue_sample:
    #sample approach (pursuit) parameters
    pursuit_velocity: 0.8
    spin_velocity: 0.5
    max_pursuit_error: 0.5
    min_pursuit_distance: 1.2
    simple_pursuit_threshold: 1.5
    #after min_pursuit reached, we move to check_distance, wait settle_time
    #and check for obstacles.  Then we make the manipulator view approach.
    settle_time: 4.0
    sample_obstacle_check_width: 0.6
    final_pursuit_step: 0.4
    square_search_size: 0.3 
    search_velocity: 0.05
