#Recovery configuration file

#Simple moves are executed first, strafes only.
#Sample detection is disabled during simple moves.
#Use with extreme caution, no obstacle checking.
#strafe example: - { angle: 45, distance: 2.0, velocity: 0.2 }
#spin example: - { angle: 90, velocity: 0.3 }
simple_moves: [
    { angle: 90 , distance: 6.0, velocity: 0.6 }
]

#These moves are executed with VFH control. Rotations
#and distance all specified relative to base_link.
#example: - { rotate: -45, distance: 10 }
moves: [
    #{ rotate: -170, distance: 2 },
    #{ rotate: -90, distance: 2 }
]

#Pursue samples during the recovery moves?
#Finding a sample will trigger pursuit, and 
#cancel the remaining recovery moves.
pursue_samples: true

#Enable beacon camera
beacon_enabled_on_entry: true
beacon_enabled_on_exit: false

#A value of 1 gets rid of the rest of the raster on the
#current spoke.  Only useful if exiting to web_manager.
slices_to_remove: 1

#Add the indices of web slices to be appended to remaining
#list of indices.  New indices added to front of list
slices_to_add: []

#Time offset: modify time remaining by this many minutes
time_offset: 0

#Available outcomes:
#web_manager = go back to the web search
#return_manager = begin beacon return
#wait_for_preempt = end level two behavior
terminal_outcome: web_manager  

