#Recovery configuration file

#Simple moves are executed first, strafes only.
#Sample detection is disabled during simple moves.
#Use with extreme caution, no obstacle checking.
#example: - { angle: 45, distance: 2.0, velocity: 0.2 }
simple_moves: [
    #{ angle: 45, distance: 2.0, velocity: 0.2 }
]

#These moves are executed with VFH control. Rotations
#and distance all specified relative to base_link.
#example: - { rotate: -45, distance: 10 }
moves: [
    { rotate: -170, distance: 2 },
    { rotate: -90, distance: 2 },
]

#Pursue samples during the recovery moves?
#Finding a sample will trigger pursuit, and 
#cancel the remaining recovery moves.
pursue_samples: false

#A value of 1 gets rid of the rest of the raster on the
#current spoke.  Only useful if exiting to web_manager.
spokes_to_remove: 0 

#Available outcomes:
#web_manager = go back to the web search
#return_manager = begin beacon return
#wait_for_preempt = end level two behavior
terminal_outcome: return_manager  

