#recovery configuration file

#list of moves to make, relative to base_link
#distances in meters, angles in degrees
moves:
    rotate: -45.0
    distance: 10.0
    rotate: 90.0
    distance: 20.0

#pursue samples seen during the recovery moves
pursue_samples: False

#remove spokes from the list? A value of 1 deletes the rest ofi
#the moves on the current spoke
spoke_to_remove: 1

#outcome defines action  to take after recovery moves are complete
#beacon_search, web_manager, etc.
terminal_outcome: web_manager  

