TrajectoryPlannerROS:
    max_vel_x: 1.5
    min_vel_x: 0.02
    max_rotational_vel: 1.0
    min_in_place_rotational_vel: 1.0

    acc_lim_th: 3.2
    acc_lim_x: 2.5
    acc_lim_y: 2.5

    holonomic_robot: true
