DWAPlannerROS:
    # rad/s^2
    acc_lim_theta: 1.5
    # m/s^2
    acc_lim_x: 2.5
    acc_lim_y: 2.5
    # total translational acceleration limit
    acc_limit_trans: 2.5

    # m/s
    max_vel_x: 2.0
    min_vel_x: 0.0
    max_vel_y: 2.0
    min_vel_y: -2.0
    min_trans_vel: 0.05
    max_trans_vel: 2.0
    # rad/s
    min_rot_vel: 0.2
    max_rot_vel: 0.8
    min_in_place_rotational_vel: 0.1

    publish_cost_grid_pc: true
    #angular_sim_granularity:
    #backward_motion_penalty:
    #forward_point_distance: 0.325
    #goal_distance_bias: 24
    #occdist_scale: 0.01
    #oscillation_reset_angle: 0.2
    #oscillation_reset_dist: 0.05
    #path_distance_bias: 32
    #prune_plan: true
    #restore_defaults: false
    #rot_stopped_vel: 0.1
    #scaling_speed: 0.25
    #max_scaling_factor: 0.2
    #sim_granularity: 0.025
    #sim_time: 1.7
    #stop_time_buffer: 0.2
    #trans_stopped_vel: 0.1
    use_dwa: true
    #vth_samples: 20
    #vx_samples: 3
    #vy_samples: 10
    #xy_goal_tolerance: 0.01
    #yaw_goal_tolerance: 0.05
    #latch_xy_goal_tolerance: false
    #controller_frequency: 20.0
    #penalize_negative_x: true
