global_frame: /odom
robot_base_frame: /base_link
transform_tolerance: 0.3

update_frequency: 2.0
publish_frequency: 1.0

footprint: [[0.2, -0.90], [0.2, 0.90], [-1.55, 0.0]]

rolling_window: true
width: 30.0
height: 30.0
resolution: 0.10

inscribed_radius: 0.4
circumscribed_radius: 0.75

plugins:
    -
        name: obstacle_layer
        type: "costmap_2d::VoxelLayer"
    -
        name: inflation_layer
        type: "costmap_2d::InflationLayer"

obstacle_layer:
    origin_z: 0.2
    z_resolution: 0.10
    z_voxels: 16
    unknown_threshold: 1
    mark_threshold: 5
    #set if you want the voxel map published
    publish_voxel_map: true
    track_unknown_space: true
    obstacle_range: 15.5
    raytrace_range: 16.0

    observation_sources: port_point_cloud center_point_cloud starboard_point_cloud
    port_point_cloud: {
        topic: /cameras/navigation/port/points2,
        data_type: PointCloud2,
        expected_update_rate: 0.2,
        observation_persistence: 0.0,
        marking: true,
        clearing: true,
        min_obstacle_height: 0.0,
        max_obstacle_height: 4.0,
        obstacle_range: 15.5,
        raytrace_range: 16.0,
        }
    center_point_cloud: {
        topic: /cameras/navigation/center/points2,
        data_type: PointCloud2,
        expected_update_rate: 0.2,
        observation_persistence: 0.0,
        marking: true,
        clearing: true,
        min_obstacle_height: 0.0,
        max_obstacle_height: 4.0,
        obstacle_range: 15.5,
        raytrace_range: 16.0,
        }
    starboard_point_cloud: {
        topic: /cameras/navigation/starboard/points2,
        data_type: PointCloud2,
        expected_update_rate: 0.2,
        observation_persistence: 0.0,
        marking: true,
        clearing: true,
        min_obstacle_height: 0.0,
        max_obstacle_height: 4.0,
        obstacle_range: 15.5,
        raytrace_range: 16.0,
        }

inflation_layer:
    cost_scaling_factor: 1.0
    inflation_radius: 2.0


