global_frame: /odom_combined
robot_base_frame: /base_footprint
update_frequency: 4.0
publish_frequency: 1.0
transffalseorm_tolerance: 1.0

footprint: [[0.2, -0.90], [0.2, 0.90], [-1.55, 0.0]]
inflation_radius: 3.5
circumscribed_radius: 1.55

cost_scaling_factor: 10.0
lethal_cost_threshold: 100
unknown_cost_value: 0
