robot_base_frame: base_link
update_frequency: 4.0
publish_frequency: 1.0
transform_tolerance: 0.3
resolution: 0.05

max_obstacle_height: 1.6
max_obstacle_range: 9.5
raytrace_range: 10.0

footprint: [[0.20, -0.98], [0.2, 0.98], [-1.50, 0.0]]
inflation_radius: 1.6

cost_scaling_factor: 10.0
lethal_cost_threshold: 100
unknown_cost_value: 10

observation_sources: point_cloud_sensor
point_cloud_sensor: {
  data_type: PointCloud2,
  topic: points2,
  observation_persistence: 0.0,
  marking: true, clearing: true,
  max_obstacle_height: 0.5, min_obstacle_height: 0.05,
  obstacle_range: 9.5, raytrace_range: 10.0}
