rolling_window: false
plugins:
    -
        name: static_map
        type: "costmap_2d::StaticLayer"
    -
        name: footprint_layer
        type: "costmap_2d::FootprintLayer"

static_map:
    unknown_cost_value: 255

    lethal_cost_threshold: 100

    map_topic: "map"
