robot_base_frame: base_link
global_frame: odom
transform_tolerance: 0.3

update_frequency: 2.0
publish_frequency: 1.0

#footprint: [[0.2, -0.90], [0.2, 0.90], [-1.55, 0.0]]

rolling_window: true
width: 20.0
height: 20.0
resolution: 0.10

robot_radius: 1.0

plugins:
    -
        name: obstacle_layer
        type: "costmap_2d::VoxelLayer"
    -
        name: inflation_layer
        type: "costmap_2d::InflationLayer"

obstacle_layer:
    origin_z: -0.5
    z_resolution: 0.125
    z_voxels: 16
    unknown_threshold: 8
    mark_threshold: 6
    #set if you want the voxel map published
    publish_voxel_map: true
    track_unknown_space: true
    obstacle_range: 10.5
    raytrace_range: 10.6

    observation_sources: port_point_cloud center_point_cloud starboard_point_cloud
    port_point_cloud: {
        topic: /cameras/navigation/port/points2,
        data_type: PointCloud2,
        expected_update_rate: 0.2,
        observation_persistence: 0.0,
        marking: true,
        clearing: true,
        min_obstacle_height: -0.5,
        max_obstacle_height: 1.5,
        obstacle_range: 10.5,
        raytrace_range: 10.6,
        }
    center_point_cloud: {
        topic: /cameras/navigation/center/points2,
        data_type: PointCloud2,
        expected_update_rate: 0.2,
        observation_persistence: 0.0,
        marking: true,
        clearing: true,
        min_obstacle_height: -0.5,
        max_obstacle_height: 1.5,
        obstacle_range: 10.5,
        raytrace_range: 10.6,
        }
    starboard_point_cloud: {
        topic: /cameras/navigation/starboard/points2,
        data_type: PointCloud2,
        expected_update_rate: 0.2,
        observation_persistence: 0.0,
        marking: true,
        clearing: true,
        min_obstacle_height: -0.5,
        max_obstacle_height: 1.5,
        obstacle_range: 10.5,
        raytrace_range: 10.6,
        }

inflation_layer:
    cost_scaling_factor: 1.0
    inflation_radius: 2.0 



