global_frame: /map
robot_base_frame: /base_link
update_frequency: 4.0
publish_frequency: 1.0
footprint: [[0.2, -0.90], [0.2, 0.90], [-1.55, 0.0]]
circumscribed_radius: 1.55

plugins:
    - { name: footprint_layer, type: "costmap_2d::FootprintLayer" }
    - { name: obstacle_layer, type: "costmap_2d::VoxelLayer" }
    - { name: inflation_layer, type: "costmap_2d::InflationLayer" }

inflation_layer:
    cost_scaling_factor: 2.0
    inflation_radius: 5.0

obstacle_layer:
    transform_tolerance: 0.3

static_layer:
    unknown_cost_value: 0
    lethal_cost_threshold: 100
