local_costmap:
    resolution: 0.10
    static_map: false
    rolling_window: true
    width: 32.0
    height: 32.0
    static_map: false
    rolling_window: true
    observation_sources: point_cloud_sensor
    point_cloud_sensor: {
        data_type: PointCloud2,
        topic: /navigation/points2,
        observation_persistence: 0.0,
        expected_update_rate: 0.1,
        marking: true, clearing: true,
        max_obstacle_height: 0.5, min_obstacle_height: 0.10,
        obstacle_range: 15.0, raytrace_range: 16.0}
    #START VOXEL STUFF
    map_type: voxel
    origin_z: 0.00
    z_resolution: 0.10
    z_voxels: 10
    unknown_threshold: 8
    mark_threshold: 3
    #set if you want the voxel map published
    publish_voxel_map: true
    #END VOXEL STUFF
