rolling_window: true
width: 30.0
height: 30.0
resolution: 0.10

inscribed_radius: 0.4
circumscribed_radius: 0.75

plugins:
    -
        name: footprint_layer
        type: "costmap_2d::FootprintLayer"
    -
        name: obstacle_layer
        type: "costmap_2d::VoxelLayer"
    -
        name: inflation_layer
        type: "costmap_2d::InflationLayer"

obstacle_layer:
    origin_z: 0.0
    z_resolution: 0.10
    z_voxels: 14
    unknown_threshold: 1
    mark_threshold: 4
    #set if you want the voxel map published
    publish_voxel_map: true
    track_unknown_space: true
    obstacle_range: 15.5
    raytrace_range: 16.0

    observation_sources: port_point_cloud center_point_cloud starboard_point_cloud
    port_point_cloud: {
        topic: /cameras/navigation/port/points2,
        data_type: PointCloud2,
        expected_update_rate: 0.2,
        observation_persistence: 0.0,
        marking: true,
        clearing: true,
        min_obstacle_height: 0.0,
        max_obstacle_height: 4.0,
        obstacle_range: 15.5,
        raytrace_range: 16.0,
        }
    center_point_cloud: {
        topic: /cameras/navigation/center/points2,
        data_type: PointCloud2,
        expected_update_rate: 0.2,
        observation_persistence: 0.0,
        marking: true,
        clearing: true,
        min_obstacle_height: 0.0,
        max_obstacle_height: 4.0,
        obstacle_range: 15.5,
        raytrace_range: 16.0,
        }
    starboard_point_cloud: {
        topic: /cameras/navigation/starboard/points2,
        data_type: PointCloud2,
        expected_update_rate: 0.2,
        observation_persistence: 0.0,
        marking: true,
        clearing: true,
        min_obstacle_height: 0.0,
        max_obstacle_height: 4.0,
        obstacle_range: 15.5,
        raytrace_range: 16.0,
        }

inflation_layer:
    cost_scaling_factor: 2.0
    inflation_radius: 5.0


