global_frame: /map
robot_base_frame: /base_link
transform_tolerance: 0.3

update_frequency: 2.0
publish_frequency: 1.0

resolution: 0.10

#footprint: [[0.2, -0.90], [0.2, 0.90], [-1.55, 0.0]]
robot_radius: 1.5
