base_global_planner: "carrot_planner/CarrotPlanner"
base_local_planner: "dwa_local_planner/DWAPlannerROS"

recovery_behaviors:
    -
       name: "conservative_reset"
       type: "clear_costmap_recovery/ClearCostmapRecovery"
    -
       name: "rotate_recovery"
       type: "rotate_recovery/RotateRecovery"
    -
       name: "aggressive_reset"
       type: "clear_costmap_recovery/ClearCostmapRecovery"

planner_frequency: 0.5
controller_frequency: 10.0

controller_patience: 15.0

clearing_radius: 0.75

conservative_reset_dist: 3.0

recovery_behavior_enabled: true

clearing_rotation_allowed: true

shutdown_costmaps: false

oscillation_timeout: 0.0

oscillation_distance: 0.5

DWAPlannerROS:
    cheat_factor: 1.0
    holonomic_robot: false
    # rad/s^2
    acc_lim_theta: 0.1
    # m/s^2
    acc_lim_x: 0.2
    acc_lim_y: 0.2
    # total translational acceleration limit
    acc_limit_trans: 0.5

    # m/s
    max_vel_x: 0.4
    min_vel_x: -0.4
    max_vel_y: 0.0
    min_vel_y: -0.0
    min_trans_vel: 0.05
    max_trans_vel: 0.45
    # rad/s
    min_rot_vel: 0.0
    max_rot_vel: 0.50
    min_in_place_rotational_vel: 0.20

    publish_cost_grid_pc: true
    # radians per sim step
    angular_sim_granularity: 0.1
    #forward_point_distance: 0.325
    #oscillation_reset_angle: 0.2
    #oscillation_reset_dist: 0.05
    backward_motion_penalty: 0.5
    occdist_scale: 1.00
    goal_distance_bias: 30.0
    path_distance_bias: 20.0
    prune_plan: false
    rot_stopped_vel: 0.05
    scaling_speed: 0.25
    max_scaling_factor: 0.2
    # cm per sim step
    sim_granularity: 0.05
    sim_time: 5.0
    #stop_time_buffer: 0.2
    trans_stopped_vel: 0.01
    use_dwa: false
    vth_samples: 11
    vx_samples: 9
    vy_samples: 1
    xy_goal_tolerance: 0.3
    yaw_goal_tolerance: 0.05
    latch_xy_goal_tolerance: true
    publish_traj_pc: true
