SBPLLatticePlanner:
    planner_type: ARAPlanner
    #planner_type: ADPlanner
    allocated_time: 10
    initial_epsilon: 3.0
    primitive_filename: motion_primitives.mprim
    #force_scratch_limit: 500
    nominalvel_mpersecs: 0.4
    timetoturn45degsinplace_secs: 2.0
    lethal_obstacle: 20
