
servo_params:
    initial_velocity: 0.05
    initial_accel: 0.05
    initial_tolerance: 0.050
    final_velocity: 0.01
    final_accel: 0.02
    final_tolerance: 0.010
    settle_time: 1.0
    try_limit: 3

manipulator_correction:
    x:  0.010
    y:  0.000
