dynamixel_test_controller1:
  controller:
    package: manipulator
    module: manipulator_joint_controller
    type: ManipulatorJointController
  joint_name: testJoint1
  joint_speed: 2.0
  joint_torque_limit: 1.0
  motor:
    id: 11
    cw_limit: 0
    ccw_limit: 6.283

dynamixel_test_controller2:
  controller:
    package: manipulator
    module: manipulator_joint_controller
    type: ManipulatorJointController
  joint_name: testJoint2
  joint_speed: 2.0
  joint_torque_limit: 1.0
  motor:
    id: 12
    cw_limit: 0
    ccw_limit: 6.283
