global_frame: /map
robot_base_frame: base_link
update_frequency: 5.0
publish_frequency: 1.0

#set if you want the voxel map published
publish_voxel_map: true

#set to true if you want to initialize the costmap from a static map
static_map: false

#begin - COMMENT these lines if you set static_map to true
rolling_window: true
width: 10.0
height: 10.0
resolution: 0.05
#end - COMMENT these lines if you set static_map to true

#map_type: costmap

#START VOXEL STUFF
map_type: voxel
origin_z: 0.0
z_resolution: 0.05
z_voxels: 10
unknown_threshold: 7
mark_threshold: 2
#END VOXEL STUFF

transform_tolerance: 0.3
max_obstacle_range: 5.0
max_obstacle_height: 0.5
max_obstacle_range: 5.0
raytrace_range: 5.0
#footprint: [[-0.75, 0.0], [0.75, 0.0], [0.0, -1.5]]
footprint: [[0.2, -0.90], [0.2, 0.90], [-1.55, 0.0]]
#robot_radius: 0.0
footprint_padding: 0.01
inflation_radius: 1.6
cost_scaling_factor: 10.0
lethal_cost_threshold: 100
observation_sources: point_cloud_sensor
point_cloud_sensor: {data_type: PointCloud2, topic: points2, observation_persistence: 1.0, marking: true, clearing: false, max_obstacle_height: 2.0, min_obstacle_height: 0.0, obstacle_range: 5.0, raytrace_range: 5.0}
