<?xml version="1.0"?>
<!-- vim: set fenc=utf-8 et sts=4 ft=xml : -->
<robot
    xmlns:xacro="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
    name="">
    <enableGravity>false</enableGravity>
    <material name="plate">
        <color rgba="0.0 0.8 0.0 1.0"/>
    </material>
    <material name="suspension">
        <color rgba="0.0 0.8 0.8 1.0"/>
    </material>
    <material name="wheel">
        <color rgba="0.1 0.1 0.1 1.0"/>
    </material>
    <material name="sensor">
        <color rgba="0.2 0.6 0.1 1.0"/>
    </material>
    <material name="lens">
        <color rgba="0.5 0.3 0.1 1.0"/>
    </material>
    <material name="carousel">
        <color rgba="0.1 0.8 0.2 1.0"/>
    </material>
    <xacro:macro name="wheel_module" params="name position">
        <joint name="${name}_steering_joint" type="revolute">
            <axis xyz="0 0 1"/>
            <limit upper="1.57" lower="-1.57" effort="100" velocity="3.14"/>
            <parent link="body_triangle"/>
            <child link="${name}_suspension"/>
            <origin xyz="${position}" rpy="0 0 1.57"/>
        </joint>
        <link name="${name}_suspension">
            <visual>
                <origin xyz="0 0 ${-suspension_length/2}" rpy="0 0 -1.57"/>
                <geometry>
                    <cylinder length="${suspension_length}" radius="0.06"/>
                </geometry>
                <material name="suspension"/>
            </visual>
        </link>
        <joint name="${name}_yoke_joint" type="fixed">
            <parent link="${name}_suspension"/>
            <child link="${name}_yoke"/>
            <!-- z puts yoke at bottom of suspension since last number is
            yoke_height/2 -->
            <origin xyz="0 0 ${-suspension_length}"/>
        </joint>
        <link name="${name}_yoke">
            <visual>
                <origin xyz="0 0 ${-yoke_height/2}" rpy="0 0 0"/>
                <geometry>
                    <box size="0.18 0.15 ${yoke_height}"/>
                </geometry>
                <material name="suspension"/>
            </visual>
        </link>
        <joint name="${name}_axle" type="continuous">
            <axis xyz="0 0 1"/>
            <limit effort="10" velocity="31.4"/>
            <parent link="${name}_yoke"/>
            <child link="${name}_wheel"/>
            <!-- 1.25 must match factor in yoke, 0.125 is (1.25-1)/2 -->
            <origin xyz="0 0 ${-axle_offset}" rpy="0 1.57 0 "/>
        </joint>
        <link name="${name}_wheel">
            <visual>
                <geometry>
                    <cylinder length="${wheel_width}" radius="${wheel_diameter/2}"/>
                </geometry>
                <material name="wheel"/>
            </visual>
        </link>
    </xacro:macro>
    <xacro:macro name="stereo_pair" params="name baseline">
        <link name="${name}_baseline_bar">
            <visual>
                <geometry>
                    <!-- numbers measured from first prototype article -->
                    <box size="${baseline-0.054} 0.0254 0.0381"/>
                </geometry>
                <material name="sensor"/>
            </visual>
        </link>
        <!-- BEGIN LEFT CAMERA -->
        <joint name="${name}_left_camera_joint" type="fixed">
            <parent link="${name}_baseline_bar"/>
            <child link="${name}_left_camera"/>
            <origin xyz="${-baseline/2} 0 0"/>
        </joint>
        <link name="${name}_left_camera">
            <visual>
                <geometry>
                    <!-- numbers measured from first prototype article -->
                    <box size="0.054 0.0635 0.0381"/>
                </geometry>
                <material name="sensor"/>
            </visual>
        </link>
        <joint name="${name}_left_camera_lens_joint" type="fixed">
            <parent link="${name}_left_camera"/>
            <child link="${name}_left_camera_lens"/>
            <!-- numbers measured from first prototype article -->
            <!-- z should be 1/2 of bar thickness to put lens on face of bar-->
            <origin xyz="0 0 0.04125"/>
        </joint>
        <link name="${name}_left_camera_lens">
            <visual>
                <geometry>
                    <!-- numbers measured from first prototype article -->
                    <cylinder length="0.0444" radius="0.015875"/>
                </geometry>
                <material name="lens"/>
            </visual>
        </link>
        <!-- END LEFT CAMERA -->
        <!-- BEGIN RIGHT CAMERA -->
        <joint name="${name}_right_camera_joint" type="fixed">
            <parent link="${name}_baseline_bar"/>
            <child link="${name}_right_camera"/>
            <origin xyz="${baseline/2} 0 0"/>
        </joint>
        <link name="${name}_right_camera">
            <visual>
                <geometry>
                    <box size="0.054 0.0635 0.0381"/>
                </geometry>
                <material name="sensor"/>
            </visual>
        </link>
        <joint name="${name}_right_camera_lens_joint" type="fixed">
            <parent link="${name}_right_camera"/>
            <child link="${name}_right_camera_lens"/>
            <origin xyz="0 0 0.04125"/>
        </joint>
        <link name="${name}_right_camera_lens">
            <visual>
                <geometry>
                    <cylinder length="0.0444" radius="0.015875"/>
                </geometry>
                <material name="lens"/>
            </visual>
        </link>
        <!-- END RIGHT CAMERA -->
    </xacro:macro>

    <!-- define suspension properties -->
    <xacro:property name="wheel_diameter" value="0.33"/>
    <xacro:property name="wheel_width" value="0.09"/>
    <xacro:property name="yoke_height" value="0.3"/>
    <xacro:property name="axle_offset" value="0.25"/>
    <xacro:property name="suspension_length" value="0.35"/>
    <xacro:property name="suspension_mounting_height" value="0.26"/>
    <!-- instantiate 3 modules -->
    <xacro:wheel_module name="stern" position="-1.126 0 ${suspension_mounting_height}"/>
    <xacro:wheel_module name="port" position="0.0 0.650 ${suspension_mounting_height}"/>
    <xacro:wheel_module name="starboard" position="0.0 -0.650 ${suspension_mounting_height}"/>
    <link name="base_link">
    </link>
    <joint name="base_joint" type="fixed">
        <parent link="base_link"/>
        <child link="body_triangle"/>
        <origin xyz="0 0 ${wheel_diameter/2 + axle_offset + suspension_length - suspension_mounting_height}" rpy="0 0 0"/>
        <!--<origin xyz="0 0 0" rpy="0 0 0"/>-->
    </joint>
    <!-- the big triangle -->
    <link name="body_triangle">
        <visual>
            <origin xyz="0.0 -0.645 0" rpy="0 0 1.57"/>
            <geometry>
                <mesh filename="package://samplereturn/Media/models/triangle.mesh.xml" scale="0.86 0.75 0.03"/>
            </geometry>
            <material name="plate"/>
        </visual>
    </link>
    <joint name="body_joint" type="fixed">
        <parent link="body_triangle"/>
        <child link="top_triangle"/>
        <origin xyz="0 0 0.155" rpy="0 0 0"/>
    </joint>
    <link name="top_triangle">
        <visual>
            <origin xyz="0.0 -0.645 0" rpy="0 0 1.57"/>
            <geometry>
                <mesh filename="package://samplereturn/Media/models/triangle.mesh.xml" scale="0.86 0.75 0.03"/>
            </geometry>
            <material name="plate"/>
        </visual>
    </link>


    <!-- instantiate navigation pair -->
    <xacro:stereo_pair name="navigation" baseline="0.30" />
    <!-- attach navigation pair -->
    <joint name="navigation_stereo_pair_joint" type="fixed">
        <parent link="body_triangle"/>
        <child link="navigation_baseline_bar"/>
        <!-- macro defines camera with lenses facing along +z -->
        <!-- rpy is pi/2 + 16.5 degree down tilt -->
        <!-- height of bottom of deck (origin) is -->
        <!-- suspension_height + yoke_height - yoke_offset + wheel_radius -->
        <!--
        suspension_height+wheel_diameter*1.25/2-wheel_diameter*0.125/2+wheel_diameter/2
        -->
        <!-- so camera should be at 1.4 - deck -->
        <origin xyz="0.015 0.0 0.990" rpy="-2.00 0 -1.57"/>
    </joint>

    <!-- instantiate manipulator pair -->
    <xacro:stereo_pair name="manipulator" baseline="0.05" />
    <!-- attach navigation pair -->
    <joint name="manipulator_stereo_pair_joint" type="fixed">
        <parent link="body_triangle"/>
        <child link="manipulator_baseline_bar"/>
        <!-- macro defines camera with lenses facing along +z -->
        <!-- rpy is pi/2 + 16.5 degree down tilt -->
        <!-- height of bottom of deck (origin) is -->
        <!-- suspension_height + yoke_height - yoke_offset + wheel_radius -->
        <!--
        suspension_height+wheel_diameter*1.25/2-wheel_diameter*0.125/2+wheel_diameter/2
        -->
        <origin xyz="0.067 0.0 0.116" rpy="-2.80 0 -1.57"/>
    </joint>

    <link name="search_camera_body">
        <visual>
            <geometry>
                <box size="0.10 0.08 0.05"/>
            </geometry>
            <material name="sensor"/>
        </visual>
    </link>
    <link name="search_camera_lens">
        <visual>
            <geometry>
                <cylinder length="0.10" radius="0.035"/>
            </geometry>
            <material name="lens"/>
        </visual>
    </link>
    <joint name="search_lens_joint" type="fixed">
        <parent link="search_camera_body"/>
        <child link="search_camera_lens"/>
        <origin xyz="0.0 0.0 0.025" rpy="0 0 0"/>
    </joint>
    <joint name="search_camera_joint" type="fixed">
        <parent link="body_triangle"/>
        <child link="search_camera_body"/>
        <origin xyz="0.10 0.0 1.0" rpy="-1.77 0 -1.57"/>
    </joint>

    <!--fake laser scanner-->
    <link name="fake_laser">
    </link>
    <joint name="fake_laser_joint" type="fixed">
        <parent link="body_triangle"/>
        <child link="fake_laser"/>
        <origin xyz="0 0 0" rpy="-1.57 0 -1.57"/>
    </joint>

    <!-- carousel -->
    <link name="carousel">
        <visual>
            <geometry>
                <cylinder length="0.216" radius="0.406"/>
            </geometry>
            <material name="carousel"/>
        </visual>
    </link>
    <joint name="carousel_joint" type="continuous">
        <parent link="body_triangle"/>
        <child link="carousel"/>
        <axis xyz="0 0 1"/>
        <origin xyz="-0.239 0.0 -0.121"/>
    </joint>
</robot>
