# This is placeholder for the file that will describe the color models
# of the samples for which to search
red_puck:
  mean: [255.0,255.0,255.0]
  covariance:
    rows: 3
    cols: 3
    data: [1, 0, 0, 0, 1, 0, 0, 0, 1]
  channel: a
  min_dist: 1000.0
orange_pipe:
  mean: [255.0,255.0,255.0]
  covariance:
    rows: 3
    cols: 3
    data: [1, 0, 0, 0, 1, 0, 0, 0, 1]
  channel: b
  min_dist: 1000.0
#mser:
#  delta:
#  min_area:
#  max_area:
#  max_variation:
#  min_diversity:
#  max_evolution:
#  area_threshold:
#  min_margin:
#  edge_blur_size:
