local_costmap:
    resolution: 0.10
    static_map: false
    rolling_window: true
    width: 15.0
    height: 15.0

    obstacle_layer:
        observation_sources: port_point_cloud center_point_cloud starboard_point_cloud
        max_obstacle_height: 0.5
        min_obstacle_height: 0.10
        obstacle_range: 15.0
        raytrace_range: 16.0
        origin_z: 0.10
        z_resolution: 0.10
        z_voxels: 16
        mark_threshold: 3
        unknown_threshold: 8
        publish_voxel_map: true

        port_point_cloud: {
            data_type: PointCloud2,
            topic: /cameras/navigation/port/points2,
            observation_persistence: 0.0,
            expected_update_rate: 0.5,
            marking: true, clearing: true,
            max_obstacle_height: 0.5, min_obstacle_height: 0.10,
            obstacle_range: 15.0, raytrace_range: 16.0}
        center_point_cloud: {
            data_type: PointCloud2,
            topic: /cameras/navigation/center/points2,
            observation_persistence: 0.0,
            expected_update_rate: 0.5,
            marking: true, clearing: true,
            max_obstacle_height: 0.5, min_obstacle_height: 0.10,
            obstacle_range: 15.0, raytrace_range: 16.0}
        starboard_point_cloud: {
            data_type: PointCloud2,
            topic: /cameras/navigation/starboard/points2,
            observation_persistence: 0.0,
            expected_update_rate: 0.5,
            marking: true, clearing: true,
            max_obstacle_height: 0.5, min_obstacle_height: 0.10,
            obstacle_range: 15.0, raytrace_range: 16.0}
