global_frame: odom

width: 20.0
height: 20.0

#set if you want the voxel map published
publish_voxel_map: true

#set to true if you want to initialize the costmap from a static map
static_map: false

#begin - COMMENT these lines if you set static_map to true
rolling_window: true
#end - COMMENT these lines if you set static_map to true

#map_type: costmap

#START VOXEL STUFF
map_type: voxel
origin_z: 0.05
z_resolution: 0.10
z_voxels: 16
unknown_threshold: 5
mark_threshold: 2
#END VOXEL STUFF
