TheSmoothPlanner:
    maximum_linear_velocity: 0.5
    linear_acceleration: 0.5
    replan_look_ahead_buffer_time: 4.0
    replan_look_ahead_time: 5.0
    delta_time_after_goal_drop_path: 20.0
    wait_on_stitched_path_duration: 20.0
    xy_goal_tolerance: 0.4
