#goal
geometry_msgs/PoseStamped target_pose
float32 velocity
bool orient_at_target
---
#result
int8 COMPLETE = 0
int8 BLOCKED = 1
int8 OFF_COURSE = 2
int8 MISSED_TARGET = 3
int8 EXTERNAL_STOP = 4
int8 ERROR = 5

int8 outcome
geometry_msgs/Point position_error
std_msgs/Float64 yaw_error
---
#feedback
geometry_msgs/Point position_error
std_msgs/Float64 yaw_error

